name: custom_detector

model:
  name: custom
  device: cuda
  input_channels: 1  # Grayscale
  num_classes: 1  # Single class for person detection

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 50
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true 