name: custom_detector

model:
  name: custom_detector
  device: cuda
  input_channels: 1  # Grayscale
  output_size: 5  # 4 for bbox + 1 for class
  backbone:
    channels: [32, 64, 128]
    kernel_size: 3
    padding: 1
  detector:
    hidden_size: 512
    dropout: 0.5

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 50
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true 