name: faster_rcnn

model:
  name: faster_rcnn
  device: cuda
  input_channels: 1  # Grayscale
  num_classes: 1  # Single class for person detection
  pretrained: true
  backbone: resnet50_fpn_v2

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 50
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true

loss:
  rpn_box_loss_weight: 1.0
  rpn_cls_loss_weight: 1.0
  box_loss_weight: 1.0
  cls_loss_weight: 1.0 