name: ssdlite

model:
  name: ssdlite
  device: cuda
  input_channels: 1  # Grayscale
  num_classes: 1  # Single class for person detection
  pretrained: true
  image_size: [640, 640]  
  backbone: mobilenet_v3_large
  strides: [16, 32, 64, 128, 256, 512]  # Flattened list

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 50
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true

augmentation:
  enabled: true
  horizontal_flip: true
  vertical_flip: false
  rotation: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  scale: [0.8, 1.2]
  translate: [0.1, 0.1]

loss:
  box_loss_weight: 1.0
  cls_loss_weight: 1.0
  smooth_l1_beta: 0.11
  negative_mining_ratio: 3
  negative_mining_threshold: 0.5 