name: custom_detector

model:
  type: custom
  backbone:
    channels: [32, 64, 128]
    kernel_size: 3
    padding: 1
  detector:
    hidden_size: 512
    dropout: 0.5
  input_channels: 1  # Grayscale
  output_size: 5  # 4 for bbox + 1 for class

loss:
  bbox_loss: mse
  cls_loss: mse
  bbox_weight: 1.0
  cls_weight: 1.0 