name: effnet

model:
  name: efficientnet
  device: cuda
  pretrained: true
  num_classes: 1  # Single class for person detection
  input_channels: 1  # Grayscale

training:
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.01
  num_epochs: 50
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true

loss:
  box_loss_weight: 1.0
  cls_loss_weight: 1.0 