defaults:
  - model: ${model}
  - dataset: flir
  - _self_

# for parallel runs training different models concurrently 
hydra:
  sweeper:
    params:
      model: choice(custom_detector,effnet,faster_rcnn,ssdlite)
    max_batch_size: 3 

# Experiment settings
experiment:
  name: ${model}_${dataset}
  seed: 42
  device: cuda

# Model parameters
model:
  device: cuda
  input_channels: 1  # Grayscale
  output_size: 5  # 4 for bbox + 1 for class
  backbone:
    channels: [32, 64, 128]
    kernel_size: 3
    padding: 1
  detector:
    hidden_size: 512
    dropout: 0.5

# Training parameters
training:
  batch_size: 16  # Good balance between speed and memory
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0005
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true

data:
  train: FLIR_ADAS_v2/images_thermal_train/data
  val: FLIR_ADAS_v2/images_thermal_val/data
  test: FLIR_ADAS_v2/images_thermal_test/data
  names: ['person']

# Logging
logging:
  save_dir: outputs/${experiment.name}
  log_interval: 10
  save_interval: 5
  metrics:
    - mAP
    - precision
    - recall
    - loss
    - learning_rate
  tensorboard: true
  wandb:
    enabled: true
    project: ir-person-detection
    tags: ${model.name}
  checkpoint:
    save_best_only: true
    monitor: val_mAP
    mode: max
  evaluation:
    save_predictions: true
    save_confusion_matrix: true
    save_pr_curve: true
    iou_threshold: 0.5
    conf_threshold: 0.25 