# Sweep configuration for parallel runs
hydra:
  run:
    dir: outputs
  sweeper:
    params:
      model: choice(custom_detector,effnet,faster_rcnn,ssdlite)
    max_batch_size: 4  # Number of parallel runs


defaults:
  - model: custom_detector  # Default model, will be overridden by sweep
  - dataset: flir
  - _self_
# Experiment settings
experiment:
  name: run_1  # Simple fixed name
  seed: 42
  device: cuda

# Model configuration
model:
  name: custom_detector  # This will be overridden by the model config
  num_classes: 1
  pretrained: true
  confidence_threshold: 0.5
  device: cuda
  input_channels: 1  # Grayscale
  output_size: 5  # 4 for bbox + 1 for class
  backbone:
    channels: [32, 64, 128]
    kernel_size: 3
    padding: 1
  detector:
    hidden_size: 512
    dropout: 0.5

# Training configuration
training:
  batch_size: 8
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  checkpoint_dir: checkpoints

# Logging configuration
logging:
  save_dir: outputs/${experiment.name}  # Only keep the save directory path
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_interval: 10
  save_interval: 5
  metrics:
    - mAP
    - precision
    - recall
    - loss
    - learning_rate
  tensorboard: true
  wandb:
    enabled: true
    project: ir-person-detection
    tags: ${model}
  checkpoint:
    save_best_only: true
    monitor: val_mAP
    mode: max
  evaluation:
    save_predictions: true
    save_confusion_matrix: true
    save_pr_curve: true
    iou_threshold: 0.5
    conf_threshold: 0.25 