name: flir

# Dataset paths
data:
  train_annotations: FLIR_ADAS_v2/images_thermal_train/coco.json
  train_images: FLIR_ADAS_v2/images_thermal_train
  val_annotations: FLIR_ADAS_v2/images_thermal_val/coco.json
  val_images: FLIR_ADAS_v2/images_thermal_val
  test_annotations: FLIR_ADAS_v2/images_thermal_test/coco.json
  test_images: FLIR_ADAS_v2/images_thermal_test
  names: ['person']

# Image configuration
image:
  size: [640, 640]  # images are already this size
  channels: 1  # greyscale 
  normalize: true
  mean: [0.485]  # mean (from single channel images)
  std: [0.229]   

# Dataset specific parameters
classes:
  - person

# Transform configuration
transform:
  train:
    - name: Normalize
      params:
        mean: ${image.mean}
        std: ${image.std}
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: ColorJitter
      params:
        brightness: 0.2
        contrast: 0.2
  val:
    - name: Normalize
      params:
        mean: ${image.mean}
        std: ${image.std}

# COCO specific settings
coco:
  format: true
  min_bbox_size: 8
  max_bbox_size: 640
  min_bbox_area: 64
  max_bbox_area: 409600  