name: flir

# Dataset paths
data:
  train_annotations: FLIR_ADAS_v2/images_thermal_train/coco.json
  train_images: FLIR_ADAS_v2/images_thermal_train
  val_annotations: FLIR_ADAS_v2/images_thermal_val/coco.json
  val_images: FLIR_ADAS_v2/images_thermal_val
  test_annotations: FLIR_ADAS_v2/images_thermal_test/coco.json
  test_images: FLIR_ADAS_v2/images_thermal_test
  names: ['person']

# Image configuration
image:
  channels: 1  # greyscale 

# Dataset specific parameters
classes:
  - person

transform: #including more augmentations to prevent overfitting 
  train:
    - name: Resize
      params:
        size: ${model.transform.input_size}
    - name: RandomRotation
      params: 
        degrees: 10 
        p: 0.3
        expand: false
    - name: RandomHorizontalFlip
      params:
        p: 0.5 
    - name: RandomVerticalFlip
      params:
        p: 0.2 
    - name: Normalize
      params:
        mean: [0.2618] 
        std: [0.1905]
    - name: ColorJitter
      params:
        brightness: 0.2 
        contrast: 0.2
        p: 0.5
    - name: RandomGaussianNoise
      params:
        mean: 0.0
        std: 0.1
        p: 0.5
    - name: RandomGamma
      params: 
        gamma: 1
        p: 0.5
  val:
    - name: Resize
      params:
        size: ${model.transform.input_size}
    - name: Normalize
      params: 
        mean: [0.4832]
        std: [0.2524]
  test:
    - name: Normalize
      params:
         mean: [0.4832]
         std: [0.2524]

# COCO specific settings
coco:
  format: true
  min_bbox_size: 8
  max_bbox_size: 640
  min_bbox_area: 64
  max_bbox_area: 409600  

  