defaults:
  - model: yolo  # or custom_detector, efficientnet, faster_rcnn, ssdlite
  - dataset: yolo
  - _self_

# Experiment settings
experiment:
  name: ${model.name}_${dataset.name}
  seed: 42
  device: ${device}

# Model parameters
model:
  device: cuda
  input_channels: 1  # Grayscale
  output_size: 5  # 4 for bbox + 1 for class
  backbone:
    channels: [32, 64, 128]
    kernel_size: 3
    padding: 1
  detector:
    hidden_size: 512
    dropout: 0.5

# Training parameters
training:
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0005
  early_stopping_patience: 5
  num_workers: 4
  pin_memory: true

#for YOLO dataset config
data:
  train: data/thermal/images/train_flir_images
  val: data/thermal/images/val_flir_images
  test: data/thermal/images/test_flir_images
  names: ['person']

# Logging
logging:
  save_dir: outputs/${experiment.name}
  log_interval: 10
  save_interval: 5 