defaults:
  - model: yolo  # or custom_detector, efficientnet, faster_rcnn, ssdlite
  - dataset: yolo
  - _self_

# Experiment settings
experiment:
  name: ${model.name}_${dataset.name}
  seed: 42
  device: ${device}

# Logging
logging:
  save_dir: outputs/${experiment.name}
  log_interval: 10
  save_interval: 5 